/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FontAwesome {
  FontAwesome._();

  static const _kFontFam = 'FontAwesome';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData heart_empty = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bookmark_empty = const IconData(0xf097, fontFamily: _kFontFam);
  static const IconData comment_empty = const IconData(0xf0e5, fontFamily: _kFontFam);
  static const IconData plus_squared = const IconData(0xf0fe, fontFamily: _kFontFam);
  static const IconData plus_squared_alt = const IconData(0xf196, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xf1d8, fontFamily: _kFontFam);
  static const IconData paper_plane_empty = const IconData(0xf1d9, fontFamily: _kFontFam);
  static const IconData television = const IconData(0xf26c, fontFamily: _kFontFam);
}
